import type { Metadata } from 'next';
import localFont from 'next/font/local';

import '@/app/globals.css';
import Footer from '@/container/Footer';
import Navbar from '@/container/Navbar';

const wantedSans = localFont({
  src: [
    {
      path: '../../public/font/WantedSans-Regular.woff2',
      style: 'normal',
      weight: '400',
    },
    {
      path: '../../public/font//WantedSans-Medium.woff2',
      style: 'normal',
      weight: '500',
    },
    {
      path: '../../public/font/WantedSans-SemiBold.woff2',
      style: 'normal',
      weight: '600',
    },
    {
      path: '../../public/font/WantedSans-Bold.woff2',
      style: 'normal',
      weight: '700',
    },
    {
      path: '../../public/font/WantedSans-ExtraBold.woff2',
      style: 'normal',
      weight: '800',
    },
    {
      path: '../../public/font/WantedSans-Black.woff2',
      style: 'normal',
      weight: '900',
    },
    {
      path: '../../public/font/WantedSans-ExtraBlack.woff2',
      style: 'normal',
      weight: '950',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Clast Cloud',
  description: 'Generated by create next app',
  icons: {
    icon: '/clast-logo-only.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR" className="h-full">
      <body className={wantedSans.className + ' h-full bg-white'}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
